config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :pictures do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture

  validates :content, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one_attached :file

  validates :file, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image,  dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @picture, notice: 'Comentario agregado con éxito.'
    else
      redirect_to @picture, alert: 'No se pudo agregar el comentario.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
    @comment = Comment.new
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to @picture, notice: 'Imagen subida con éxito.'
    else
      render :new, alert: 'No se pudo subir la imagen.'
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:name, :content, :image)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KariPic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container mt-4">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>

  <%= form.submit 'Save Picture', class: 'btn btn-primary' %>
<% end %>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">
  <p>
    <strong>Name:</strong>
    <%= picture.name %>
  </p>
  <% if picture.image.attached? %>
    <%= image_tag picture.image, class: 'img-fluid', alt: picture.name %>
  <% else %>
    <p>No image attached</p>
  <% end %>
  <h2>Comments:</h2>
  <% picture.comments.each do |comment| %>
    <div class="media mb-3">
      <% if comment.user.profile_image.attached? %>
        <%= image_tag comment.user.profile_image.variant(resize_to_fill: [50, 50]), class: "mr-3 rounded-circle", alt: comment.user.name %>
      <% else %>
        <%= image_tag 'default_profile.png', class: "mr-3 rounded-circle", size: "50x50", alt: "Default profile image" %>
      <% end %>
      <div class="media-body">
        <h5 class="mt-0"><%= comment.user.name %></h5>
        <p><%= comment.content %></p>
      </div>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <h3>Add a Comment:</h3>
    <%= form_with(model: [picture, Comment.new]) do |form| %>
      <div class="form-group">
        <%= form.label :content %>
        <%= form.text_area :content, class: "form-control" %>
      </div>
      <%= form.submit "Post Comment", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<% content_for :title, "Editing picture" %>

<h1>Editing picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Show this picture", @picture %> |
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/index.html.erb
<h1>All Pictures</h1>

<% @pictures.each do |picture| %>
  <div class="mb-4">
    <%= link_to picture_path(picture) do %>
      <%= render picture %>
    <% end %>
  </div>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Upload New Picture', new_picture_path, class: 'btn btn-primary' %>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<%= render @picture %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">KariPic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'New Picture', new_picture_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>